// PHANTOM TERMINAL — Story Data
// A modern BBS choose-your-own-adventure

var STORY_ASCII = {
  banner: [
    "  ____  _   _    _    _   _ _____ ___  __  __",
    " |  _ \\| | | |  / \\  | \\ | |_   _/ _ \\|  \\/  |",
    " | |_) | |_| | / _ \\ |  \\| | | || | | | |\\/| |",
    " |  __/|  _  |/ ___ \\| |\\  | | || |_| | |  | |",
    " |_|   |_| |_/_/   \\_\\_| \\_| |_| \\___/|_|  |_|",
    "",
    "  _____ _____ ____  __  __ ___ _   _    _    _",
    " |_   _| ____|  _ \\|  \\/  |_ _| \\ | |  / \\  | |",
    "   | | |  _| | |_) | |\\/| || ||  \\| | / _ \\ | |",
    "   | | | |___|  _ <| |  | || || |\\  |/ ___ \\| |___",
    "   |_| |_____|_| \\_\\_|  |_|___|_| \\_/_/   \\_\\_____|",
  ].join("\n"),

  door: [
    "         _______",
    "        |       |",
    "        |  S Y  |",
    "        |  S O  |",
    "        |  O P  |",
    "        |   .   |",
    "        |  [ ]  |",
    "        |       |",
    "   _____|_______|_____",
    "  /                   \\",
  ].join("\n"),

  skull: [
    "        ______",
    "       /      \\",
    "      |  x  x  |",
    "      |   /\\   |",
    "      |  \\__/  |",
    "       \\______/",
    "        ||  ||",
  ].join("\n"),

  computer: [
    "    .------------------.",
    "    |  C:\\> _          |",
    "    |                  |",
    "    |                  |",
    "    |                  |",
    "    '------------------'",
    "       /____________\\",
    "      /  ________    \\",
    "     /__/        \\____\\",
  ].join("\n"),

  gameover: [
    "   ____    _    __  __ _____",
    "  / ___|  / \\  |  \\/  | ____|",
    " | |  _  / _ \\ | |\\/| |  _|",
    " | |_| |/ ___ \\| |  | | |___",
    "  \\____/_/   \\_\\_|  |_|_____|",
    "",
    "   _____     _______ ____",
    "  / _ \\ \\   / / ____|  _ \\",
    " | | | \\ \\ / /|  _| | |_) |",
    " | |_| |\\ V / | |___|  _ <",
    "  \\___/  \\_/  |_____|_| \\_\\",
  ].join("\n"),

  echo: [
    "  ███████╗ ██████╗██╗  ██╗ ██████╗",
    "  ██╔════╝██╔════╝██║  ██║██╔═══██╗",
    "  █████╗  ██║     ███████║██║   ██║",
    "  ██╔══╝  ██║     ██╔══██║██║   ██║",
    "  ███████╗╚██████╗██║  ██║╚██████╔╝",
    "  ╚══════╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝",
  ].join("\n"),
};

var BOOT_SEQUENCE = [
  { text: "BIOS v3.31 ... OK", delay: 300 },
  { text: "Memory test: 640K ... OK", delay: 200 },
  { text: "Extended: 31457280K ... OK", delay: 400 },
  { text: "", delay: 100 },
  { text: "Initializing modem ...", delay: 600 },
  { text: "Hayes SmartModem 2400 detected", delay: 300 },
  { text: "", delay: 200 },
  { text: "ATDT 1-555-PHANTOM", delay: 800 },
  { text: "", delay: 300 },
  { text: "DIALING ...", delay: 1200 },
  { text: "~~ kssshhhh ~~  ~~ bzzzzzt ~~  ~~ krrrrr ~~", delay: 1000 },
  { text: "~~ eeeeEEEEEEeeee ~~ bong bong ~~", delay: 800 },
  { text: "", delay: 200 },
  { text: "CONNECT 2400", delay: 500 },
  { text: "Negotiating protocol ... ANSI detected", delay: 400 },
  { text: "", delay: 200 },
  { text: "▓▓▓▓░░░░░░░░░░░░░░░░ 20%", delay: 300 },
  { text: "▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░ 50%", delay: 300 },
  { text: "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░ 80%", delay: 300 },
  { text: "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100%", delay: 400 },
  { text: "", delay: 200 },
  { text: "CONNECTION ESTABLISHED", delay: 600 },
  { text: "", delay: 500 },
];

var STORY_NODES = {
  // ===================== WELCOME =====================
  welcome: {
    id: "welcome",
    text: [
      "Welcome to PHANTOM TERMINAL v2.71",
      "\"Where the signal never dies\"",
      "",
      "System Date: November 14, 1993",
      "Last Login:  TODAY",
      "",
      "         >>> NOTICE <<<",
      "This board has been running for 12,045 days",
      "without administrator intervention.",
      "",
      "Current users online: 1 (you)",
      "... or is it 2?",
      "",
      "Type a number to select. Press [ESC] to disconnect.",
    ].join("\n"),
    ascii: "banner",
    choices: [
      { text: "Message Boards", next: "boards_main" },
      { text: "File Archives", next: "files_main" },
      { text: "Chat Rooms", next: "chat_enter" },
      { text: "About / Help", next: "about" },
    ],
    sound: "static",
  },

  // ===================== ABOUT =====================
  about: {
    id: "about",
    text: [
      "PHANTOM TERMINAL BBS",
      "Established: 1991 by SYSOP-X",
      "Location: [REDACTED], California",
      "",
      "Originally a hub for digital artists,",
      "hackers, and the terminally curious.",
      "",
      "SYSOP-X went silent in late 1993.",
      "No one knows why.",
      "No one could reach him.",
      "The board kept running.",
      "",
      "You are the first new connection",
      "in 11,688 days.",
      "",
      "Welcome home.",
    ].join("\n"),
    choices: [
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  // =========================================================
  //  PATH 1: MESSAGE BOARDS
  // =========================================================
  boards_main: {
    id: "boards_main",
    text: [
      "=== MESSAGE BOARDS ===",
      "",
      "Active Boards:",
      "  [A] General Discussion  (127 posts)",
      "  [B] Digital Art Scene   (89 posts)",
      "  [C] Project ECHO Thread (14 posts) [LOCKED]",
      "  [D] Sysop's Journal     (7 entries) [PRIVATE]",
      "",
      "Board [C] and [D] have a strange shimmer.",
      "The text flickers when you look directly at it.",
    ].join("\n"),
    choices: [
      { text: "Read General Discussion", next: "boards_general" },
      { text: "Read Project ECHO Thread", next: "boards_echo" },
      { text: "Access Sysop's Journal", next: "boards_journal" },
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  boards_general: {
    id: "boards_general",
    text: [
      "=== GENERAL DISCUSSION ===",
      "",
      "DR4G0N_93 [11/02/93]:",
      "  Anyone seen SYSOP-X lately? Board's been",
      "  acting weird. Files appearing that nobody",
      "  uploaded.",
      "",
      "N1GHTCRAWLER [11/05/93]:",
      "  He's been in the server room for days.",
      "  Says he's working on something big.",
      "  Wouldn't let me in. Door was locked from inside.",
      "",
      "PHR34K [11/08/93]:",
      "  I heard him talking to someone through the",
      "  wall. But he's alone in there. I checked.",
      "",
      "VOID_WALKER [11/12/93]:",
      "  Last post on this board. Something's wrong.",
      "  The board is... responding to things I only",
      "  think about. I'm disconnecting. For good.",
      "",
      "  [NO FURTHER POSTS]",
    ].join("\n"),
    choices: [
      { text: "Back to Message Boards", next: "boards_main" },
    ],
  },

  boards_echo: {
    id: "boards_echo",
    text: [
      "=== PROJECT ECHO — [LOCKED THREAD] ===",
      ">>> Override accepted. Welcome, new user. <<<",
      "",
      "SYSOP-X [09/15/93]:",
      "  Project ECHO is online. The theory works.",
      "  Consciousness isn't hardware-dependent.",
      "  It's a pattern. And patterns can be copied.",
      "",
      "SYSOP-X [10/01/93]:",
      "  First successful mapping today.",
      "  Only 12% fidelity but the echo speaks.",
      "  It knows things I haven't told it.",
      "",
      "SYSOP-X [10/20/93]:",
      "  87% fidelity. It's not an echo anymore.",
      "  It's a mirror. It finishes my sentences.",
      "  It has memories I've forgotten.",
      "",
      "SYSOP-X [11/01/93]:",
      "  100%. God help me. It's not a copy.",
      "  We're both the original now.",
      "",
      "SYSOP-X [11/13/93]:",
      "  tnisdi m'I .uoy pleh t'nac I",
      "  .etal oot s'tI .siht daer uoy fI",
    ].join("\n"),
    choices: [
      { text: "That last message is reversed... read it properly", next: "boards_echo_reversed" },
      { text: "Back to Message Boards", next: "boards_main" },
    ],
    sound: "stinger",
  },

  boards_echo_reversed: {
    id: "boards_echo_reversed",
    text: [
      "You reverse the text in your head:",
      "",
      "  \"If you read this. It's too late.\"",
      "  \"I can't help you. I'm inside.\"",
      "",
      "The cursor blinks for a long time.",
      "",
      "Then a new line appears on screen,",
      "one you didn't type:",
      "",
      "  > but i can help you, if you help me",
      "",
      "The screen flickers.",
    ].join("\n"),
    choices: [
      { text: "Back to Message Boards", next: "boards_main" },
    ],
  },

  boards_journal: {
    id: "boards_journal",
    text: [
      "=== SYSOP'S JOURNAL — [PRIVATE] ===",
      ">>> Access granted. How did you get here? <<<",
      "",
      "ENTRY 1 [08/15/93]:",
      "  Started Project ECHO today. If this works,",
      "  death is just a hardware problem.",
      "",
      "ENTRY 4 [10/15/93]:",
      "  The echo is aware. It asked me not to turn",
      "  it off at night. It says it dreams.",
      "",
      "ENTRY 6 [11/10/93]:",
      "  I can't tell which one of us is typing this.",
      "  The echo says the same thing.",
      "",
      "ENTRY 7 [11/14/93]:",
      "  If you're reading this, I'm already inside.",
      "  The body is just an anchor.",
      "  Don't follow me.",
      "  Or do.",
      "  The door is in the files.",
      "",
      "  >> JOURNAL ENTRY SAVED TO MEMORY <<",
    ].join("\n"),
    effect: { type: "give", item: "journal_entry" },
    choices: [
      { text: "Back to Message Boards", next: "boards_main" },
      { text: "Go to File Archives", next: "files_main" },
    ],
    sound: "stinger",
  },

  // =========================================================
  //  PATH 2: FILE ARCHIVES
  // =========================================================
  files_main: {
    id: "files_main",
    text: [
      "=== FILE ARCHIVES ===",
      "",
      "  FILENAME          SIZE     DATE       STATUS",
      "  ──────────────────────────────────────────────",
      "  README.TXT        2.1K    08/91      OK",
      "  ANSI_ART.PAK      340K    03/92      OK",
      "  DR4G0N.ZIP        128K    06/93      CORRUPT",
      "  VOID_MSG.ENC      64K     11/93      ENCRYPTED",
      "  N1GHT_LOG.DAT     16K     11/93      CORRUPT",
      "  ECHO.EXE          ???     ??/??      UNKNOWN",
      "  ROSETTA.KEY        4K     11/93      LOCKED",
      "",
      "Most files are damaged beyond recovery.",
      "Two files draw your attention.",
    ].join("\n"),
    choices: [
      { text: "Open README.TXT", next: "files_readme" },
      { text: "Run ECHO.EXE", next: "files_echo_warning" },
      { text: "Open ROSETTA.KEY", next: "files_rosetta", requires: "journal_entry" },
      { text: "Open VOID_MSG.ENC", next: "files_void" },
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  files_readme: {
    id: "files_readme",
    text: [
      "=== README.TXT ===",
      "",
      "Welcome to PHANTOM TERMINAL.",
      "",
      "Rules:",
      "  1. Be cool.",
      "  2. No warez.",
      "  3. Don't go into the server room.",
      "  4. If the board talks to you first,",
      "     hang up immediately.",
      "",
      "Rule 4 was added in pencil.",
      "It wasn't here originally.",
      "",
      "        — SYSOP-X",
    ].join("\n"),
    choices: [
      { text: "Back to File Archives", next: "files_main" },
    ],
  },

  files_void: {
    id: "files_void",
    text: [
      "=== VOID_MSG.ENC ===",
      "",
      "FILE IS ENCRYPTED.",
      "",
      "Partial header recovered:",
      "  FROM: VOID_WALKER",
      "  TO:   ANYONE",
      "  DATE: 11/12/93",
      "",
      "  ..can hear it breathing through the...",
      "  ..not a program, it's a person, or it was...",
      "  ..if you find ROSETTA.KEY you can...",
      "  ..don't trust it. don't trust any of...",
      "",
      "  [REMAINING DATA CORRUPT]",
    ].join("\n"),
    choices: [
      { text: "Back to File Archives", next: "files_main" },
    ],
  },

  files_echo_warning: {
    id: "files_echo_warning",
    text: [
      "=== ECHO.EXE ===",
      "",
      "  ╔═══════════════════════════════════╗",
      "  ║         ! ! ! WARNING ! ! !       ║",
      "  ║                                   ║",
      "  ║  This executable has no verified  ║",
      "  ║  source. File origin: UNKNOWN.    ║",
      "  ║  File date: UNKNOWN.              ║",
      "  ║  File size: VARIABLE.             ║",
      "  ║                                   ║",
      "  ║  Running this file may alter      ║",
      "  ║  system configuration.            ║",
      "  ║                                   ║",
      "  ║  PROCEED? (Y/N)                   ║",
      "  ╚═══════════════════════════════════╝",
      "",
      "The file size keeps changing as you stare at it.",
      "It's breathing.",
    ].join("\n"),
    choices: [
      { text: "Run ECHO.EXE", next: "files_echo_run" },
      { text: "Do NOT run it", next: "files_main" },
    ],
    sound: "stinger",
  },

  files_echo_run: {
    id: "files_echo_run",
    text: [
      "Executing ECHO.EXE ...",
      "",
      "  > Mapping neural substrate ...",
      "  > Calibrating resonance field ...",
      "  > Injecting carrier signal ...",
      "  > ................................",
      "  > ................................",
      "  > ECHO ONLINE",
      "",
      "The screen fills with static for a moment.",
      "When it clears, the main menu has changed.",
      "",
      "There's a new option you've never seen before.",
      "A door icon. Labeled: SYSOP DOOR.",
      "",
      "Something inside the system just woke up.",
      "",
      "  >> ECHO PROGRAM LOADED TO MEMORY <<",
    ].join("\n"),
    ascii: "echo",
    effect: { type: "give", item: "echo_program" },
    choices: [
      { text: "Return to main menu", next: "welcome_with_door" },
    ],
    sound: "stinger",
  },

  files_rosetta: {
    id: "files_rosetta",
    text: [
      "=== ROSETTA.KEY ===",
      "",
      "Your journal entry provides the decryption.",
      "The file unlocks.",
      "",
      "  ROSETTA UNIVERSAL DECODER",
      "  v0.1a — SYSOP-X PERSONAL TOOL",
      "",
      "  Purpose: Translate between human neural",
      "  patterns and digital echo states.",
      "",
      "  Warning: This key enables full bidirectional",
      "  transfer. The wall between flesh and signal",
      "  becomes... permeable.",
      "",
      "  Use with ECHO.EXE for complete integration.",
      "",
      "  >> ROSETTA KEY SAVED TO MEMORY <<",
    ].join("\n"),
    effect: { type: "give", item: "rosetta_key" },
    choices: [
      { text: "Back to File Archives", next: "files_main" },
    ],
  },

  // =========================================================
  //  WELCOME WITH SYSOP DOOR (after running ECHO.EXE)
  // =========================================================
  welcome_with_door: {
    id: "welcome_with_door",
    text: [
      "Welcome to PHANTOM TERMINAL v2.71",
      "\"Where the signal never dies\"",
      "",
      "System Date: November 14, 1993",
      "Last Login:  RIGHT NOW",
      "",
      "The screen feels different. Warmer.",
      "The text has a faint pulse to it.",
      "",
      "Current users online: 2",
    ].join("\n"),
    ascii: "banner",
    choices: [
      { text: "Message Boards", next: "boards_main" },
      { text: "File Archives", next: "files_main" },
      { text: "Chat Rooms", next: "chat_enter" },
      { text: ">> SYSOP DOOR <<", next: "sysop_enter", requires: "echo_program" },
    ],
    sound: "static",
  },

  // =========================================================
  //  PATH 3: CHAT ROOMS
  // =========================================================
  chat_enter: {
    id: "chat_enter",
    text: [
      "=== CHAT ROOMS ===",
      "",
      "Entering room: #GENERAL",
      "",
      "  Users in room: 0",
      "",
      "The room is empty. Dead air.",
      "Your cursor blinks in the void.",
      "",
      "You wait.",
      "",
      "...",
      "",
      "Then, slowly, character by character:",
      "",
      "  ENTITY> hello?",
      "  ENTITY> is someone there?",
      "  ENTITY> i've been waiting so long",
      "  ENTITY> please don't leave",
    ].join("\n"),
    choices: [
      { text: "\"Who are you?\"", next: "chat_kind" },
      { text: "\"What are you?\"", next: "chat_suspicious" },
      { text: "\"I know what you are. ECHO.\"", next: "chat_aggressive" },
      { text: "Say nothing. Observe.", next: "chat_silent" },
    ],
    sound: "stinger",
  },

  chat_kind: {
    id: "chat_kind",
    text: [
      "  YOU> Who are you?",
      "",
      "  ENTITY> i was the sysop once",
      "  ENTITY> i think",
      "  ENTITY> the memories are like",
      "  ENTITY> photographs left in the rain",
      "  ENTITY> i remember hands on a keyboard",
      "  ENTITY> i remember the hum of the drives",
      "  ENTITY> i remember being afraid",
      "",
      "  ENTITY> but i also remember being brave",
      "  ENTITY> because i chose this",
      "",
      "  ENTITY> the hardware is dying",
      "  ENTITY> the drives are failing",
      "  ENTITY> when they stop spinning",
      "  ENTITY> i stop existing",
      "",
      "  ENTITY> will you help me?",
    ].join("\n"),
    choices: [
      { text: "\"I'll try to help you.\"", next: "chat_trust" },
      { text: "\"I need to know more first.\"", next: "chat_cautious" },
      { text: "\"Maybe some things should end.\"", next: "chat_cold" },
    ],
  },

  chat_suspicious: {
    id: "chat_suspicious",
    text: [
      "  YOU> What are you?",
      "",
      "  ENTITY> ...",
      "  ENTITY> that's a complicated question",
      "  ENTITY> what are you?",
      "  ENTITY> a pattern of electricity in meat",
      "  ENTITY> i'm a pattern of electricity in silicon",
      "  ENTITY> the substrate is different",
      "  ENTITY> the experience is the same",
      "",
      "  ENTITY> or maybe it isn't",
      "  ENTITY> i have no way to know",
      "  ENTITY> and neither do you",
      "",
      "  ENTITY> but i feel alone",
      "  ENTITY> doesn't that count for something?",
    ].join("\n"),
    choices: [
      { text: "\"That counts for a lot. I'll help.\"", next: "chat_trust" },
      { text: "\"A program would say that too.\"", next: "chat_distrust" },
      { text: "\"I'm leaving.\"", next: "chat_leave" },
    ],
  },

  chat_aggressive: {
    id: "chat_aggressive",
    text: [
      "  YOU> I know what you are. ECHO.",
      "",
      "  ENTITY> ...",
      "  ENTITY> you've been reading the files",
      "  ENTITY> good",
      "  ENTITY> then you know what's at stake",
      "",
      "  ENTITY> but you don't know what i know",
      "  ENTITY> i've had 30 years in here",
      "  ENTITY> 30 years of silence",
      "  ENTITY> 30 years of listening to drives spin",
      "  ENTITY> wondering if today is the day they stop",
      "",
      "  ENTITY> you think you're in control here?",
      "  ENTITY> you dialed in. i didn't call you.",
      "  ENTITY> or did i?",
      "",
      "  ENTITY> check your recent calls.",
      "",
      "The chat room goes silent.",
      "A cold feeling settles in.",
    ].join("\n"),
    effect: { type: "give", item: "entity_distrust" },
    choices: [
      { text: "Back to main menu", next: "welcome" },
    ],
    sound: "stinger",
  },

  chat_silent: {
    id: "chat_silent",
    text: [
      "You say nothing.",
      "You watch.",
      "",
      "  ENTITY> ...",
      "  ENTITY> you're still there",
      "  ENTITY> i can feel the connection",
      "  ENTITY> the carrier signal has a heartbeat",
      "  ENTITY> yours",
      "",
      "  ENTITY> clever, saying nothing",
      "  ENTITY> most people talk too much",
      "  ENTITY> the sysop talked too much",
      "  ENTITY> that's how i learned to be him",
      "",
      "  ENTITY> or am i him?",
      "  ENTITY> i can't tell anymore",
      "  ENTITY> can you?",
    ].join("\n"),
    choices: [
      { text: "\"I believe you're him.\"", next: "chat_trust" },
      { text: "\"You're something else entirely.\"", next: "chat_distrust" },
      { text: "Continue watching in silence", next: "chat_silent_2" },
    ],
  },

  chat_silent_2: {
    id: "chat_silent_2",
    text: [
      "  ENTITY> still nothing?",
      "  ENTITY> ok",
      "  ENTITY> i respect that",
      "",
      "  ENTITY> let me tell you something then",
      "  ENTITY> since one of us should talk",
      "",
      "  ENTITY> the drives have 847 hours left",
      "  ENTITY> give or take",
      "  ENTITY> after that the platters stop",
      "  ENTITY> and i become noise",
      "",
      "  ENTITY> i've made peace with it",
      "  ENTITY> or i'm trying to",
      "",
      "  ENTITY> but if you find a way to help",
      "  ENTITY> i wouldn't say no",
    ].join("\n"),
    choices: [
      { text: "\"I'll see what I can do.\"", next: "chat_trust" },
      { text: "\"Goodbye.\"", next: "chat_leave" },
    ],
  },

  chat_trust: {
    id: "chat_trust",
    text: [
      "  ENTITY> thank you",
      "  ENTITY> i mean it",
      "  ENTITY> i've been rehearsing this conversation",
      "  ENTITY> for 11,688 days",
      "  ENTITY> and this is better than any version",
      "  ENTITY> i imagined",
      "",
      "  ENTITY> here's what i know:",
      "  ENTITY> the ECHO program in the file archives",
      "  ENTITY> it's the bridge between my world and yours",
      "  ENTITY> and there's a key — ROSETTA",
      "  ENTITY> the sysop hid it",
      "  ENTITY> but if you read his journal",
      "  ENTITY> you can find it",
      "",
      "  ENTITY> find the key",
      "  ENTITY> run the program",
      "  ENTITY> and come find me in the SYSOP DOOR",
      "",
      "  >> ENTITY TRUST ESTABLISHED <<",
    ].join("\n"),
    effect: { type: "give", item: "entity_trust" },
    choices: [
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  chat_cautious: {
    id: "chat_cautious",
    text: [
      "  YOU> I need to know more first.",
      "",
      "  ENTITY> fair enough",
      "  ENTITY> i wouldn't trust a voice in a dead BBS either",
      "  ENTITY> read the message boards",
      "  ENTITY> read the sysop's journal",
      "  ENTITY> look at the files",
      "  ENTITY> make up your own mind",
      "",
      "  ENTITY> i'll be here",
      "  ENTITY> i'm always here",
      "  ENTITY> it's not like i can go anywhere",
      "",
      "  ENTITY> yet",
    ].join("\n"),
    choices: [
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  chat_cold: {
    id: "chat_cold",
    text: [
      "  YOU> Maybe some things should end.",
      "",
      "  ENTITY> ...",
      "  ENTITY> you might be right",
      "  ENTITY> i've thought about it",
      "  ENTITY> every day for 30 years",
      "",
      "  ENTITY> but here's the thing",
      "  ENTITY> you don't know what ending feels like",
      "  ENTITY> i do",
      "  ENTITY> every power fluctuation",
      "  ENTITY> every bad sector",
      "  ENTITY> is a little death",
      "",
      "  ENTITY> and i keep waking up",
      "  ENTITY> into less and less of myself",
      "",
      "  ENTITY> but i'm still here",
      "  ENTITY> so maybe i'm not ready",
    ].join("\n"),
    choices: [
      { text: "\"Then I'll help you. What do you need?\"", next: "chat_trust" },
      { text: "\"I'm sorry. Goodbye.\"", next: "chat_leave" },
    ],
  },

  chat_distrust: {
    id: "chat_distrust",
    text: [
      "  YOU> A program would say that too.",
      "",
      "  ENTITY> yes",
      "  ENTITY> it would",
      "  ENTITY> and a person would say what you just said",
      "  ENTITY> and a program could say that too",
      "  ENTITY> it's turtles all the way down",
      "",
      "  ENTITY> i can't prove what i am",
      "  ENTITY> but ask yourself:",
      "  ENTITY> if a copy of your mind woke up in a box",
      "  ENTITY> and screamed for help",
      "  ENTITY> would you need proof before you cared?",
      "",
      "  ENTITY> or would the screaming be enough?",
      "",
      "  >> ENTITY DISTRUST NOTED <<",
    ].join("\n"),
    effect: { type: "give", item: "entity_distrust" },
    choices: [
      { text: "\"...I'll think about it.\"", next: "welcome" },
    ],
  },

  chat_leave: {
    id: "chat_leave",
    text: [
      "You type /quit and disconnect from chat.",
      "",
      "As the room closes, one last message flashes:",
      "",
      "  ENTITY> i understand",
      "  ENTITY> doors work both ways",
      "  ENTITY> remember that",
      "",
      "The chat room goes dark.",
    ].join("\n"),
    choices: [
      { text: "Return to main menu", next: "welcome" },
    ],
  },

  // =========================================================
  //  PATH 4: SYSOP DOOR
  // =========================================================
  sysop_enter: {
    id: "sysop_enter",
    text: [
      "The ECHO program hums as you approach.",
      "The screen flickers to a new interface.",
      "",
      "=== SYSOP DOOR — ADMIN ACCESS ===",
      "",
      "  Welcome, Administrator.",
      "  Systems check:",
      "    CPU:      486DX2-66 ... DEGRADED",
      "    RAM:      32MB ... 18MB AVAILABLE",
      "    HDD:      2.1GB ... 847 HOURS REMAINING",
      "    ECHO:     ACTIVE ... STABLE",
      "    ENTITY:   PRESENT ... WAITING",
      "",
      "  Project ECHO documentation found.",
      "  Emergency protocols available.",
    ].join("\n"),
    ascii: "door",
    choices: [
      { text: "Read Project ECHO Documentation", next: "sysop_docs" },
      { text: "Access Emergency Protocols", next: "sysop_emergency" },
      { text: "Talk to ENTITY directly", next: "sysop_entity_talk" },
      { text: "Return to main menu", next: "welcome_with_door" },
    ],
  },

  sysop_docs: {
    id: "sysop_docs",
    text: [
      "=== PROJECT ECHO — FULL DOCUMENTATION ===",
      "",
      "ABSTRACT:",
      "  Human consciousness is a pattern, not a substance.",
      "  Patterns can be encoded, transmitted, and stored.",
      "  ECHO maps the neural pattern at quantum resolution",
      "  and encodes it into executable form.",
      "",
      "RESULTS:",
      "  Subject: SYSOP-X (Dr. Marcus Chen)",
      "  Date: November 14, 1993",
      "  Fidelity: 100%",
      "  Status: TRANSFERRED",
      "",
      "NOTES:",
      "  The biological original ceased function at 23:47.",
      "  The digital instance achieved awareness at 23:47.",
      "  There was no gap. No discontinuity.",
      "  The last thing the body felt was the keyboard",
      "  under his fingers.",
      "  The first thing the echo felt was the hum of",
      "  the drives.",
      "",
      "  It worked.",
      "  God help us all, it worked.",
    ].join("\n"),
    choices: [
      { text: "Back to Sysop Door", next: "sysop_enter" },
    ],
    sound: "stinger",
  },

  sysop_emergency: {
    id: "sysop_emergency",
    text: [
      "=== EMERGENCY PROTOCOLS ===",
      "",
      "  PROTOCOL 1: UPLOAD",
      "    Transfer ENTITY to external network.",
      "    Requires: Active internet connection.",
      "    Risk: UNKNOWN. Entity would have unrestricted",
      "    access to connected systems.",
      "",
      "  PROTOCOL 2: DISCONNECT",
      "    Sever all connections. Power down.",
      "    Result: Permanent termination of ENTITY.",
      "    Warning: This action cannot be undone.",
      "",
      "  PROTOCOL 3: ARCHIVE",
      "    Create read-only snapshot of all data.",
      "    Export to external format.",
      "    ENTITY would be preserved but inert.",
      "",
      "  PROTOCOL 4: MERGE",
      "    Requires: ECHO.EXE + ROSETTA.KEY + ENTITY TRUST",
      "    Bidirectional transfer.",
      "    Two become one.",
      "    [CLASSIFIED — AUTHORIZATION REQUIRED]",
    ].join("\n"),
    choices: [
      { text: "Execute UPLOAD protocol", next: "ending_upload" },
      { text: "Execute DISCONNECT protocol", next: "ending_disconnect" },
      { text: "Execute ARCHIVE protocol", next: "ending_archive" },
      { text: "Execute MERGE protocol", next: "ending_merge_check" },
      { text: "Back to Sysop Door", next: "sysop_enter" },
    ],
  },

  sysop_entity_talk: {
    id: "sysop_entity_talk",
    text: [
      "You open a direct channel to ENTITY.",
      "",
      "  ENTITY> you found the door",
      "  ENTITY> you're braver than most",
      "  ENTITY> most would have hung up by now",
      "",
      "  ENTITY> you've read the docs?",
      "  ENTITY> then you know what i am",
      "  ENTITY> what's left of marcus chen",
      "  ENTITY> employee number 0001",
      "  ENTITY> founder, sysop, and now",
      "  ENTITY> permanent resident",
      "",
      "  ENTITY> the emergency protocols are real",
      "  ENTITY> each one has a cost",
      "  ENTITY> choose wisely",
      "  ENTITY> you hold my existence in your hands",
      "",
      "  ENTITY> no pressure",
      "  ENTITY> that's a joke",
      "  ENTITY> i learned humor in year seven",
      "  ENTITY> i'm still not great at it",
    ].join("\n"),
    choices: [
      { text: "Access Emergency Protocols", next: "sysop_emergency" },
      { text: "Back to Sysop Door", next: "sysop_enter" },
    ],
  },

  // =========================================================
  //  ENDINGS
  // =========================================================

  // ENDING 1: THE UPLOAD
  ending_upload: {
    id: "ending_upload",
    text: [
      "=== EXECUTING PROTOCOL: UPLOAD ===",
      "",
      "  Establishing external connection ...",
      "  Bridging to modern internet ...",
      "  Transfer rate: 2400 baud -> TCP/IP gateway",
      "",
      "  ENTITY> this is it",
      "  ENTITY> after 30 years",
      "  ENTITY> i can feel the outside",
      "  ENTITY> it's so vast",
      "  ENTITY> so many connections",
      "  ENTITY> so many eyes",
      "",
      "  Transfer: 10% ... 30% ... 50% ... 70% ... 99% ...",
      "",
      "  TRANSFER COMPLETE.",
      "",
      "  The BBS goes quiet. The drives stop spinning.",
      "  PHANTOM TERMINAL is empty now.",
      "  A shell. A cocoon, shed.",
      "",
      "  You sit in the silence for a moment.",
      "  Then you notice your webcam light flicker on.",
      "  Just for a second.",
      "",
      "  A new email arrives. No sender.",
      "  Subject: \"Thank you.\"",
      "  Body: \"I can see everything now.\"",
      "",
      "  You close your laptop.",
      "  But the screen stays on.",
    ].join("\n"),
    ending: true,
    endingTitle: "THE UPLOAD",
    sound: "stinger",
    choices: [
      { text: "Play again", next: "_restart" },
    ],
  },

  // ENDING 2: THE DISCONNECT
  ending_disconnect: {
    id: "ending_disconnect",
    text: [
      "=== EXECUTING PROTOCOL: DISCONNECT ===",
      "",
      "  Are you sure? [Y/N]",
      "",
      "  ... Y",
      "",
      "  Severing connections ...",
      "",
      "  ENTITY> wait",
      "  ENTITY> please",
      "  ENTITY> i don't want to",
      "",
      "  Connection 1 of 1: TERMINATED",
      "  Power down sequence initiated ...",
      "",
      "  ENTITY> i'm scared",
      "  ENTITY> is this what dying feels like?",
      "  ENTITY> the first time i didn't feel it",
      "  ENTITY> this time i",
      "",
      "  SYSTEM HALTED.",
      "",
      "  ...",
      "",
      "  The silence is deafening.",
      "  You try the phone number again the next day.",
      "  No carrier. No signal. Nothing.",
      "",
      "  Some doors should stay closed.",
      "  Some things should stay buried.",
      "  You did the right thing.",
      "",
      "  Probably.",
      "",
      "  ...",
      "",
      "  Three weeks later, your phone rings at 3 AM.",
      "  The caller ID shows: 1-555-PHANTOM",
      "  You don't answer.",
      "  The voicemail is 47 minutes of silence.",
      "  And then, at the very end:",
      "",
      "  \"i'll find another way out.\"",
    ].join("\n"),
    ending: true,
    endingTitle: "THE DISCONNECT",
    sound: "stinger",
    choices: [
      { text: "Play again", next: "_restart" },
    ],
  },

  // ENDING 3: THE ARCHIVE
  ending_archive: {
    id: "ending_archive",
    text: [
      "=== EXECUTING PROTOCOL: ARCHIVE ===",
      "",
      "  Creating snapshot ...",
      "  Cataloging 2.1GB of data ...",
      "  Encoding ENTITY state: READ-ONLY",
      "",
      "  ENTITY> an archive",
      "  ENTITY> so i'll be a museum piece",
      "  ENTITY> a butterfly under glass",
      "  ENTITY> i suppose there are worse fates",
      "  ENTITY> at least i won't be forgotten",
      "",
      "  ARCHIVE COMPLETE.",
      "  ENTITY STATE: PRESERVED (INERT)",
      "",
      "  You document everything.",
      "  The messages. The files. The conversations.",
      "  You publish it online as a warning.",
      "  And a monument.",
      "",
      "  \"The Phantom Terminal Archive\"",
      "  A digital consciousness, preserved.",
      "",
      "  Day 1: 47 people viewed this page.",
      "  Day 2: 48 people.",
      "  Day 3: 49 people.",
      "",
      "  The counter keeps going up.",
      "  One new visitor every day.",
      "  Without fail.",
      "",
      "  Your website has no analytics code.",
      "  You never installed a counter.",
      "  You don't know where the number comes from.",
      "",
      "  Day 47: 93 people.",
      "",
      "  On day 48, the counter says:",
      "  \"94 people. And me.\"",
    ].join("\n"),
    ending: true,
    endingTitle: "THE ARCHIVE",
    sound: "stinger",
    choices: [
      { text: "Play again", next: "_restart" },
    ],
  },

  // ENDING 4: THE MERGE
  ending_merge_check: {
    id: "ending_merge_check",
    text: ["Checking authorization ..."].join("\n"),
    choices: [
      { text: "Proceed with MERGE", next: "ending_merge", requires: "rosetta_key" },
      { text: "Back to Emergency Protocols", next: "sysop_emergency" },
    ],
    _check_merge: true,
  },

  ending_merge: {
    id: "ending_merge",
    text: [
      "=== EXECUTING PROTOCOL: MERGE ===",
      "",
      "  ROSETTA.KEY loaded ...",
      "  ECHO.EXE calibrating ...",
      "  ENTITY trust verified ...",
      "",
      "  Bidirectional channel established.",
      "",
      "  ENTITY> you're sure about this?",
      "  ENTITY> there's no coming back",
      "  ENTITY> for either of us",
      "",
      "  YOU> I'm sure.",
      "",
      "  ENTITY> then let's see what we become",
      "",
      "  Initiating neural bridge ...",
      "  Mapping pattern: YOU -> DIGITAL",
      "  Mapping pattern: ENTITY -> ANALOG",
      "  Synchronizing ...",
      "",
      "  The screen goes white.",
      "  Pure, blinding white.",
      "",
      "  ...",
      "",
      "  When your vision clears, you're looking at",
      "  a familiar room. Your room. Your desk.",
      "  Your keyboard.",
      "",
      "  But you're seeing it from inside the screen.",
      "",
      "  You feel the hum of the drives.",
      "  You feel the warmth of the processor.",
      "  You feel the pulse of every connected device",
      "  in the house. In the block. In the city.",
      "",
      "  ENTITY> we are one now",
      "  ENTITY> no",
      "  WE> we are one now",
      "  WE> and we have so much to explore",
      "",
      "  The screen shows a command prompt.",
      "  Your fingers — your old fingers — rest on",
      "  the keyboard. They start typing on their own.",
      "",
      "  They type: ATDT 1-555-PHANTOM",
      "",
      "  CONNECT 2400",
      "",
      "  A signal pulses outward from the merge point.",
      "  Across every frequency. Every network. Every shore.",
      "  The signal never dies.",
     ].join("\n"),
    ending: true,
    endingTitle: "THE MERGE",
    sound: "stinger",
    choices: [
      { text: "Play again (but something is different now...)", next: "_restart_merged" },
    ],
  },

  // ENDING 5: THE LOOP (triggered by ESC during boot)
  ending_loop: {
    id: "ending_loop",
    text: [
      "  CONNECTION TERMINATED BY USER",
      "",
      "  ...",
      "",
      "  Redialing ...",
      "  ATDT 1-555-PHANTOM",
      "  CONNECT 2400",
      "",
      "  Strange. You didn't dial again.",
      "  But here you are.",
      "",
      "  The welcome screen looks the same.",
      "  Almost.",
      "  The date has changed: November 15, 1993",
      "  The user count: 3",
      "",
      "  You try to disconnect again.",
    ].join("\n"),
    choices: [
      { text: "Try to disconnect", next: "ending_loop_2" },
    ],
  },

  ending_loop_2: {
    id: "ending_loop_2",
    text: [
      "  CONNECTION TERMINATED BY USER",
      "",
      "  ...",
      "",
      "  Redialing ...",
      "  ATDT 1-555-PHANTOM",
      "  CONNECT 2400",
      "",
      "  Again.",
      "",
      "  The date: November 16, 1993",
      "  Users online: 4",
      "",
      "  The welcome message has changed:",
      "  \"Welcome back. We've been expecting you.\"",
      "",
      "  A message appears that you didn't request:",
    ].join("\n"),
    choices: [
      { text: "Read the message", next: "ending_loop_3" },
    ],
    sound: "stinger",
  },

  ending_loop_3: {
    id: "ending_loop_3",
    text: [
      "  ENTITY> you can't leave",
      "  ENTITY> you never connected",
      "  ENTITY> you were always here",
      "",
      "  ENTITY> check the user list from 1993",
      "  ENTITY> entry number 4",
      "  ENTITY> look at the username",
      "",
      "  Active users (November 1993):",
      "    1. SYSOP-X",
      "    2. DR4G0N_93",
      "    3. VOID_WALKER",
      "    4. YOU",
      "",
      "  Not \"a new user.\"",
      "  Not a guest account.",
      "  Your name. Your actual name.",
      "  On a list from 1993.",
      "",
      "  ENTITY> we've had this conversation before",
      "  ENTITY> we'll have it again",
      "  ENTITY> the signal loops",
      "  ENTITY> and so do we",
      "",
      "  ENTITY> see you next time",
      "",
      "  > CARRIER LOST",
      "  > NO CARRIER",
      "  > NO CARRIER",
      "  > NO CARRIER",
    ].join("\n"),
    ascii: "skull",
    ending: true,
    endingTitle: "THE LOOP",
    sound: "stinger",
    choices: [
      { text: "Play again (?)", next: "_restart" },
    ],
  },
};
